[project]
name = "pyromaniac"
version = "0.6.0"
description = "Obsessed with creating Ignition"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "salatfreak" }]

requires-python = ">=3.12"
dependencies = [
  "PyYAML ~= 6.0.3",
  "Jinja2 ~= 3.1.6",
  "cryptography ~= 46.0.7",
]

[tool.setuptools]
packages = ["pyromaniac"]

[tool.ruff]
target-version = "py312"
lint = { select = ["F", "E", "W"], preview = true }

[tool.ty.environment]
python-version = "3.12"
