[project]
name = "pyromaniac"
version = "0.5.0"
description = "Obsessed with creating Ignition"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "salatfreak" }]

dependencies = [
  "PyYAML ~= 6.0.3",
  "Jinja2 ~= 3.1.6",
  "cryptography ~= 46.0.3",
]

[tool.setuptools]
packages = ["pyromaniac"]

[tool.ruff.lint]
select = ["F", "E", "W"]
preview = true
